# Generated by Django 6.0 on 2026-01-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0002_roulettehistory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettehistory',
            name='memo',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roulettehistory',
            name='recipe_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
