# Generated by Django 6.0 on 2026-01-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_roulettehistory_memo_roulettehistory_recipe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettehistory',
            name='is_post',
            field=models.BooleanField(default=False),
        ),
    ]
